name: Brian Chase, Economic Researcher
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
collections:
  education:
    order:
      - johns_hopkins.md
      - william_mary.md
    output: true
  experience:
    output: true
    order:
      - basis.md
      - hznorm.md
      - hz4z.md
      - berger.md
      - bear_american.md
