name: Brian Chase, Economic Researcher
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
collections:
  education:
    output: true
    sort_by: year
  experience:
    sort_by: years
    output: true
