name: Brian Chase, Economic Researcher
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
collections:
  education:
    sort_by: order
    output: true
  experience:
    sort_by: order
    output: true
